package org.scalamu.plugin

import com.typesafe.scalalogging.Logger
import org.scalamu.common.MutantId
import org.scalamu.plugin.util.{CompilerAccess, GlobalExtractors, TreeSanitizer}

import scala.tools.nsc.Global

/**
 * Base trait for all mutations.
 */
trait Mutation {
  def mutatingTransformer(
    global: Global,
    config: MutationConfig
  ): MutatingTransformer

  def description: String
}

abstract class MutatingTransformer(
  private val config: MutationConfig
)(
  override implicit val global: Global
) extends CompilerAccess
    with GlobalExtractors
    with TreeSanitizer {

  override def isMutationGuard(symbolName: String): Boolean =
    config.guard.isGuardSymbol(symbolName)

  trait Transformer extends global.Transformer {
    import global._

    private val fullName: Symbol => String = _.fullNameString

    private val excludedSymbols: Seq[String] = Seq(
      "scala.reflect.api.Exprs.Expr",
      "scala.reflect.api.Trees.Tree",
      "scala.reflect.macros.Universe.Tree"
    )

    private var currentPackage: String = _

    private final def maybeUpdatePackage(tree: Tree): Tree = tree match {
      case t: DefTree =>
        Option(t.symbol) match {
          case Some(sym) => currentPackage = sym.enclosingPackage.fullName
          case None      =>
        }
        t
      case t => t
    }

    override final def transform(tree: Tree): Tree = tree match {
      case t if t.attachments.all.toString.contains("MacroExpansionAttachment") => tree
      case t if Option(t.symbol).exists(fullName andThen config.filter)         => tree
      case DefDef(mods, _, _, _, _, _) if mods.isSynthetic || mods.isMacro      => tree
      case macroImpl: DefDef
          if Option(macroImpl.tpt.symbol).exists(fullName andThen excludedSymbols.contains) =>
        tree
      case ClassDef(_, _, _, Template(parents, _, _))
          if parents.map(_.tpe.typeSymbol.fullName).contains("scala.reflect.api.TypeCreator") =>
        tree
      case t @ GuardedMutant(guard, mutated, alternative) =>
        // do not mutate code generated by another mutation
        treeCopy.If(t, guard, mutated, transform(alternative))
      case _ =>
        maybeUpdatePackage(tree)
        (mutate andThen retype).applyOrElse(tree, continue)
    }

    protected final def generateMutantReport(tree: Tree, mutated: Tree): MutantId = {
      val info = MutantInfo(
        mutation,
        currentRunId,
        currentPackage,
        tree.pos,
        showCode(tree),
        showCode(mutated)
      )
      if (!tree.pos.isDefined) {
        Transformer.log.info(s"Mutant $info in tree $tree has undefined position.")
      }
      config.reporter.report(info)
      info.id
    }

    private val continue: PartialFunction[Tree, Tree] = PartialFunction(super.transform)

    protected final val retype: PartialFunction[Tree, Tree] = PartialFunction(typer.typed)

    protected def mutate: PartialFunction[Tree, Tree]

    private def sanitizeTree(tree: Tree): Tree =
      if (config.sanitizeTrees) SanitizingTransformer(tree) else tree

    protected final def guard(mutated: Tree, alternative: Tree, id: MutantId): Tree =
      config.guard(global)(sanitizeTree(mutated), sanitizeTree(alternative), id)
  }

  object Transformer {
    private val log = Logger[Transformer]
  }

  protected def mutation: Mutation

  protected def transformer: Transformer

  def apply(tree: global.Tree): global.Tree = transformer.transform(tree)
}
