package org.scalamu.plugin

import org.scalamu.plugin.util.{CompilerAccess, GlobalExtractors, TreeSanitizer}

import scala.tools.nsc.Global

/**
 * Base trait for all mutations.
 */
trait Mutation {
  def mutatingTransformer(
    global: Global,
    config: MutationConfig
  ): MutatingTransformer
}

abstract class MutatingTransformer(
  private val config: MutationConfig
)(
  override implicit val global: Global
) extends CompilerAccess
    with GlobalExtractors
    with TreeSanitizer {

  trait Transformer extends global.Transformer {
    import global._

    private val fullName: Symbol => String = _.fullNameString

    override final def transform(tree: Tree): Tree = tree match {
      case t if t.attachments.all.toString.contains("MacroExpansionAttachment") => tree
      case t if Option(t.symbol).exists(fullName andThen config.filter)         => tree
      case DefDef(mods, _, _, _, _, _) if mods.isSynthetic                      => tree
      case ClassDef(_, _, _, Template(parents, _, _))
          if parents.map(_.tpe.typeSymbol.fullName).contains("scala.reflect.api.TypeCreator") =>
        tree
      case GuardedMutation(guard, mutated, alternative) =>
        // do not mutate code generated by another mutation
        q"if ($guard) $mutated else ${transform(alternative)}"
      case _ => (mutate andThen retype).applyOrElse(tree, continue)
    }

    protected final def reportMutation(tree: Tree, mutated: Tree): Unit = {
      val info = MutantInfo(
        mutation,
        currentRunId,
        tree.pos,
        show(tree),
        show(mutated)
      )
      config.reporter.report(info)
    }

    private def continue: PartialFunction[Tree, Tree] = PartialFunction(super.transform)

    protected final def retype: PartialFunction[Tree, Tree] = PartialFunction(typer.typed)

    protected def mutate: PartialFunction[Tree, Tree]

    protected final def guard(mutated: Tree, untouched: Tree): Tree = {
      val sanitized = if (config.sanitizeTrees) removeNestedMutants(mutated) else mutated
      config.guard(global)(sanitized, untouched)
    }
  }

  protected def mutation: Mutation

  protected def transformer: Transformer

  def apply(tree: global.Tree): global.Tree = transformer.transform(tree)
}
